{
 "title": "FE Mon (___REPLACEWITHSITENAME___)",
 "tags": [
  "FE",
  "___REPLACEWITHSITENAME___"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "ICMP round trip time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s", "label": "RTT" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{job=~\"___REPLACEWITHSITENAME____ICMP\",phase=\"rtt\"}) by (Sitename) > 0",
     "legendFormat": "RTT"
    }
   ]
  },
  {
   "title": "ICMP Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "packet loss" }
   ],
   "targets": [
    {
     "expr": "1-avg_over_time(probe_success{job=~\"___REPLACEWITHSITENAME____ICMP\", sitename=~\"$Sitename\"}[30s])",
     "legendFormat": "packet loss"
    }
   ]
  },
  {
   "title": "Status of Services (DTN-RM)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum by (servicename,service_state) (service_state{service_state=\"OK\",sitename=\"___REPLACEWITHSITENAME___\"}) ",
     "legendFormat": "{{servicename}} {{service_state}}"
    }
   ]
  },
  {
   "title": "Service status (timeline) (DTN-RM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{sitename=\"___REPLACEWITHSITENAME___\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "Service status (___REPLACEWITHSITENAME___) FAILED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{job=\"___REPLACEWITHSITENAME____STATE\", service_state=\"FAILED\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "Service status (___REPLACEWITHSITENAME___) UNKNOWN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{job=\"___REPLACEWITHSITENAME____STATE\", service_state=\"UNKNOWN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "Service status (___REPLACEWITHSITENAME___) OK",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{job=\"___REPLACEWITHSITENAME____STATE\", service_state=\"OK\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=~\"___REPLACEWITHSITENAME____HTTPS\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=~\"___REPLACEWITHSITENAME____HTTPS\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "IP protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ip_protocol{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=~\"___REPLACEWITHSITENAME____HTTPS\"} - time()",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_tls_version_info{job=~\"___REPLACEWITHSITENAME____HTTPS\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}